name: Build Docker Image

on:
  pull_request:
    branches:
    - master

jobs:
  build-docker-image:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - uses: docker/build-push-action@v1
      with:
        push: false
        dockerfile: Dockerfile
